name: ci pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: iterative/setup-cml@v2

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main file
        run: |
          python main.py

      - name: Run Tests
        run: |
          python -m unittest discover

      - name: Create CML report
      env:
        REPO_TOKEN: ${{ secrets.PROJECT_ENV_TOKEN }}
      run: |

        python main.py > results.txt
        echo "---" >> report.md
        cat results.txt >> report.md

        cml comment create report.md